export const defaultActivities = (
  userId: string
): Partial<ActivityEntity>[] => [
  {
    status: 'active',
    penalty: false,
    name: 'Passion project',
    count: 0,
    countMode: 'minutes',
    countCalc: 30,
    icon: 'laptop',
    userId,
    createdAt: new Date(),
    pattern: [
      { shape: 'circle', size: 33, r: 4, right: '7%', top: '-4%' },
      { shape: 'triangle', size: 22, r: 334, left: '-5%', top: '6%' },
      { shape: 'triangle', size: 40, r: 87, right: '-9%', bottom: '3%' },
      { shape: 'circle', size: 44, r: 170, left: '20%', top: '-3%' },
    ],
  },
  {
    status: 'active',
    penalty: false,
    name: 'Exercise ',
    count: 0,
    countMode: 'minutes',
    countCalc: 30,
    icon: 'dumbbell',
    userId,
    createdAt: new Date(),
    pattern: [
      { shape: 'triangle', size: 21, r: 152, right: '26%', top: '4%' },
      { shape: 'circle', size: 29, r: 200, right: '4%', bottom: '-14%' },
      { shape: 'triangle', size: 26, r: 337, right: '31%', bottom: '5%' },
    ],
  },
  {
    status: 'active',
    penalty: false,
    name: 'Meditating',
    count: 0,
    countMode: 'minutes',
    countCalc: 30,
    icon: 'yin-yang',
    userId,
    createdAt: new Date(),
    pattern: [
      { shape: 'triangle', size: 32, r: 84, right: '-10%', bottom: '15%' },
      { shape: 'triangle', size: 37, r: 209, right: '18%', bottom: '15%' },
      { shape: 'triangle', size: 37, r: 110, right: '-2%', top: '-5%' },
    ],
  },
  {
    status: 'active',
    penalty: false,
    name: 'Reading',
    count: 0,
    countMode: 'minutes',
    countCalc: 30,
    icon: 'book-spells',
    userId,
    createdAt: new Date(),
    pattern: [
      { shape: 'circle', size: 41, r: 349, left: '27%', bottom: '2%' },
      { shape: 'circle', size: 34, r: 144, right: '17%', bottom: '-2%' },
      { shape: 'circle', size: 37, r: 240, left: '27%', bottom: '-1%' },
      { shape: 'circle', size: 22, r: 86, right: '27%', top: '12%' },
    ],
  },
  {
    status: 'active',
    penalty: true,
    name: 'Smoking',
    count: 0,
    countMode: 'times',
    countCalc: 30,
    icon: 'smoking',
    userId,
    createdAt: new Date(),
    pattern: [
      { shape: 'triangle', size: 44, r: 54, right: '10%', bottom: '-9%' },
      { shape: 'triangle', size: 37, r: 309, left: '3%', bottom: '16%' },
      { shape: 'triangle', size: 44, r: 88, right: '12%', bottom: '-2%' },
      { shape: 'triangle', size: 21, r: 100, right: '14%', top: '-6%' },
    ],
  },
  {
    status: 'active',
    penalty: true,
    name: 'Junk food',
    count: 0,
    countMode: 'times',
    countCalc: 30,
    icon: 'french-fries',
    userId,
    createdAt: new Date(),
    pattern: [
      { shape: 'triangle', size: 21, r: 206, left: '24%', top: '3%' },
      { shape: 'triangle', size: 37, r: 224, left: '-7%', top: '2%' },
      { shape: 'triangle', size: 32, r: 306, right: '12%', top: '-14%' },
      { shape: 'circle', size: 34, r: 7, right: '10%', bottom: '5%' },
    ],
  },
];
